# Generated by Django 5.2.4 on 2025-08-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_messag_convers_0f1a53_idx',
        ),
    ]
