# Generated by Django 5.2.4 on 2025-08-15 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_all_guest_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='uniq_vendor_client_conversation',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='client_unread_count',
            new_name='unread_count',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='client_last_read_at',
            new_name='user1_last_read_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='vendor_last_read_at',
            new_name='user2_last_read_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='client_user',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='vendor_unread_count',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_is_vendor',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='uniq_user1_user2_conversation'),
        ),
    ]
