# Generated by Django 5.2.4 on 2025-01-08 15:30

from django.db import migrations, models


def migrate_client_data_to_customuser(apps, schema_editor):
    """Mevcut client profil verilerini CustomUser'a taşı"""
    ClientProfile = apps.get_model('clients', 'ClientProfile')
    CustomUser = apps.get_model('core', 'CustomUser')
    
    for client_profile in ClientProfile.objects.all():
        user = client_profile.user
        
        # Eğer CustomUser'da first_name yoksa, ClientProfile'dan al
        if not user.first_name and hasattr(client_profile, 'first_name'):
            user.first_name = client_profile.first_name or ''
        
        # Eğer CustomUser'da last_name yoksa, ClientProfile'dan al
        if not user.last_name and hasattr(client_profile, 'last_name'):
            user.last_name = client_profile.last_name or ''
        
        # Eğer CustomUser'da phone_number yoksa, ClientProfile'dan al
        if not user.phone_number and hasattr(client_profile, 'phone'):
            user.phone_number = client_profile.phone or ''
        
        # Eğer CustomUser'da avatar yoksa, ClientProfile'dan al
        if not user.avatar and hasattr(client_profile, 'avatar') and client_profile.avatar:
            user.avatar = client_profile.avatar
        
        # Eğer CustomUser'da avatar yoksa, ClientProfile'dan profile_photo'yu al
        if not user.avatar and hasattr(client_profile, 'profile_photo') and client_profile.profile_photo:
            user.avatar = client_profile.profile_photo
        
        user.save()


def reverse_migrate_client_data(apps, schema_editor):
    """Geri almak için (gerekirse)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('core', '0005_customuser_avatar_alter_customuser_first_name_and_more'),
    ]

    operations = [
        # Önce veri taşıma
        migrations.RunPython(migrate_client_data_to_customuser, reverse_migrate_client_data),
        
        # Sonra field'ları kaldır
        migrations.RemoveField(
            model_name='clientprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile_photo',
        ),
    ]
