# Generated by Django 5.2.4 on 2025-08-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientprofile_address_alter_clientprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='district',
        ),
    ]
