# Generated by Django 5.2.4 on 2025-11-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Anahtar')),
                ('value', models.TextField(verbose_name='Değer')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Admin Ayarı',
                'verbose_name_plural': 'Admin Ayarları',
                'db_table': 'AdminSettings',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
                'db_table': 'BlogCategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10, verbose_name='Seviye')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Modül')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('activity_type', models.CharField(choices=[('system', 'Sistem'), ('user_registered', 'Kullanıcı Kaydı'), ('vendor_created', 'Esnaf Oluşturuldu'), ('support_ticket', 'Destek Talebi'), ('blog_published', 'Blog Yayınlandı'), ('user_verified', 'Kullanıcı Doğrulandı'), ('vendor_verified', 'Esnaf Doğrulandı')], db_index=True, default='system', max_length=20, verbose_name='Aktivite Türü')),
                ('activity_data', models.JSONField(blank=True, default=dict, verbose_name='Aktivite Verisi')),
            ],
            options={
                'verbose_name': 'Sistem Logu',
                'verbose_name_plural': 'Sistem Logları',
                'db_table': 'SystemLog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('notification_type', models.CharField(choices=[('new_user', 'Yeni Kullanıcı'), ('new_vendor', 'Yeni Esnaf'), ('support_ticket', 'Destek Talebi'), ('system_alert', 'Sistem Uyarısı'), ('upgrade_request', 'Yükseltme Talebi')], max_length=20, verbose_name='Bildirim Türü')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('related_object_id', models.CharField(blank=True, max_length=100, verbose_name='İlgili Obje ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Admin Bildirimi',
                'verbose_name_plural': 'Admin Bildirimleri',
                'db_table': 'AdminNotification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read'], name='AdminNotifi_is_read_50c795_idx'), models.Index(fields=['notification_type'], name='AdminNotifi_notific_6b3c89_idx'), models.Index(fields=['created_at'], name='AdminNotifi_created_554ec2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editör'), ('support', 'Teknik Destek')], db_index=True, max_length=20)),
                ('permission', models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'Kullanıcı Yönetimi'), ('vendors', 'Esnaf Yönetimi'), ('support', 'Destek Talepleri'), ('blog', 'Blog Yönetimi'), ('content', 'İçerik Yönetimi'), ('analytics', 'İstatistikler'), ('settings', 'Sistem Ayarları'), ('definitions', 'Tanımlamalar'), ('live_support', 'Canlı Destek'), ('logs', 'Sistem Logları')], db_index=True, max_length=20)),
                ('can_read', models.BooleanField(db_index=True, default=False)),
                ('can_write', models.BooleanField(db_index=True, default=False)),
                ('can_delete', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Admin İzni',
                'verbose_name_plural': 'Admin İzinleri',
                'db_table': 'AdminPermission',
                'indexes': [models.Index(fields=['role', 'permission'], name='AdminPermis_role_9eb18e_idx'), models.Index(fields=['role', 'can_read'], name='AdminPermis_role_fdaa34_idx'), models.Index(fields=['role', 'can_write'], name='AdminPermis_role_77905e_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editör'), ('support', 'Teknik Destek')], db_index=True, max_length=20)),
                ('is_superuser', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('password', models.CharField(max_length=128)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Kullanıcı',
                'verbose_name_plural': 'Admin Kullanıcılar',
                'db_table': 'AdminUser',
                'indexes': [models.Index(fields=['email'], name='AdminUser_email_ff4319_idx'), models.Index(fields=['role'], name='AdminUser_role_204fd8_idx'), models.Index(fields=['is_superuser'], name='AdminUser_is_supe_9c25de_idx'), models.Index(fields=['is_active'], name='AdminUser_is_acti_9ac5d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Özet')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Öne Çıkan Görsel')),
                ('featured_image_alt', models.CharField(blank=True, max_length=150, verbose_name='Öne Çıkan Görsel Alt Metin')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı'), ('archived', 'Arşivlendi')], default='draft', max_length=20, verbose_name='Durum')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Açıklama')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Anahtar Kelimeler')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='OG Başlık')),
                ('og_description', models.TextField(blank=True, max_length=200, verbose_name='OG Açıklama')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='blog/og/', verbose_name='OG Görsel')),
                ('og_alt', models.CharField(blank=True, max_length=150, verbose_name='OG Görsel Alt Metin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('author_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.adminuser', verbose_name='Yazar (Admin)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.blogcategory', verbose_name='Kategori')),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts_created', to='admin_panel.adminuser', verbose_name='Oluşturan (Admin)')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'db_table': 'BlogPost',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Domain Adı')),
                ('registrar', models.CharField(blank=True, max_length=255, verbose_name='Kayıt Şirketi')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Kayıt Tarihi')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('expiring_soon', 'Yakında Dolacak'), ('error', 'Hata')], default='active', max_length=20, verbose_name='Durum')),
                ('days_until_expiry', models.IntegerField(blank=True, null=True, verbose_name='Kalan Gün')),
                ('nameservers', models.JSONField(blank=True, default=list, verbose_name="Name Server'lar")),
                ('admin_email', models.EmailField(blank=True, max_length=254, verbose_name='Admin E-posta')),
                ('tech_email', models.EmailField(blank=True, max_length=254, verbose_name='Teknik E-posta')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Otomatik Yenileme')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Son Kontrol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domainler',
                'db_table': 'Domain',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='Domain_status_9e620a_idx'), models.Index(fields=['expiration_date'], name='Domain_expirat_5cb4d8_idx'), models.Index(fields=['days_until_expiry'], name='Domain_days_un_cec6be_idx')],
            },
        ),
    ]
