# Generated by Django 5.2.4 on 2025-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editör'), ('support', 'Teknik Destek')], db_index=True, max_length=20)),
                ('permission', models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'Kullanıcı Yönetimi'), ('vendors', 'Esnaf Yönetimi'), ('support', 'Destek Talepleri'), ('blog', 'Blog Yönetimi'), ('content', 'İçerik Yönetimi'), ('analytics', 'İstatistikler'), ('settings', 'Sistem Ayarları'), ('live_support', 'Canlı Destek'), ('logs', 'Sistem Logları')], db_index=True, max_length=20)),
                ('can_read', models.BooleanField(db_index=True, default=False)),
                ('can_write', models.BooleanField(db_index=True, default=False)),
                ('can_delete', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Admin İzni',
                'verbose_name_plural': 'Admin İzinleri',
                'indexes': [models.Index(fields=['role', 'permission'], name='admin_panel_role_60d3a6_idx'), models.Index(fields=['role', 'can_read'], name='admin_panel_role_521e8a_idx'), models.Index(fields=['role', 'can_write'], name='admin_panel_role_2b4089_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
