# Generated by Django 5.2.4 on 2025-10-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_adminpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editör'), ('support', 'Teknik Destek')], db_index=True, max_length=20)),
                ('is_superuser', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('password', models.CharField(max_length=128)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Kullanıcı',
                'verbose_name_plural': 'Admin Kullanıcılar',
                'indexes': [models.Index(fields=['email'], name='admin_panel_email_bd495f_idx'), models.Index(fields=['role'], name='admin_panel_role_d87ea4_idx'), models.Index(fields=['is_superuser'], name='admin_panel_is_supe_d13ec3_idx'), models.Index(fields=['is_active'], name='admin_panel_is_acti_f1b7ab_idx')],
            },
        ),
    ]
