# Generated by Django 5.2.4 on 2025-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_blogpost_admin_panel_status_d5765c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['is_read'], name='admin_panel_is_read_6353ea_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['notification_type'], name='admin_panel_notific_ce6f83_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['created_at'], name='admin_panel_created_a628f4_idx'),
        ),
    ]
