# Generated by Django 5.2.4 on 2025-10-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_adminnotification_admin_panel_is_read_6353ea_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=500, verbose_name='Sayfa Yolu')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='Sayfa Başlığı')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Kalma Süresi (saniye)')),
            ],
            options={
                'verbose_name': 'Sayfa Görüntüleme',
                'verbose_name_plural': 'Sayfa Görüntülemeleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VisitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Tarih')),
                ('total_visitors', models.PositiveIntegerField(default=0, verbose_name='Toplam Ziyaretçi')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Benzersiz Ziyaretçi')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='Sayfa Görüntüleme')),
                ('avg_session_duration', models.FloatField(default=0, verbose_name='Ortalama Oturum Süresi')),
                ('desktop_visitors', models.PositiveIntegerField(default=0, verbose_name='Masaüstü Ziyaretçi')),
                ('mobile_visitors', models.PositiveIntegerField(default=0, verbose_name='Mobil Ziyaretçi')),
                ('tablet_visitors', models.PositiveIntegerField(default=0, verbose_name='Tablet Ziyaretçi')),
                ('top_countries', models.JSONField(default=dict, verbose_name='En Çok Ziyaret Eden Ülkeler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Ziyaretçi Analitiği',
                'verbose_name_plural': 'Ziyaretçi Analitikleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(max_length=64, unique=True, verbose_name='Oturum Hash')),
                ('ip_hash', models.CharField(max_length=64, verbose_name='IP Hash')),
                ('user_agent_hash', models.CharField(max_length=64, verbose_name='User Agent Hash')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Ülke Kodu')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('device_type', models.CharField(choices=[('desktop', 'Masaüstü'), ('mobile', 'Mobil'), ('tablet', 'Tablet')], default='desktop', max_length=20, verbose_name='Cihaz Türü')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='İlk Ziyaret')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Son Ziyaret')),
                ('page_views', models.PositiveIntegerField(default=1, verbose_name='Sayfa Görüntüleme')),
                ('session_duration', models.PositiveIntegerField(default=0, verbose_name='Oturum Süresi (saniye)')),
                ('referrer_domain', models.CharField(blank=True, max_length=255, verbose_name='Referrer Domain')),
            ],
            options={
                'verbose_name': 'Ziyaretçi Oturumu',
                'verbose_name_plural': 'Ziyaretçi Oturumları',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.DeleteModel(
            name='AnalyticsData',
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['first_visit'], name='admin_panel_first_v_fb0732_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['last_visit'], name='admin_panel_last_vi_f4b4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['country_code'], name='admin_panel_country_dc6f55_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['device_type'], name='admin_panel_device__0fc3b4_idx'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_view_records', to='admin_panel.visitorsession'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_path'], name='admin_panel_page_pa_f48a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['timestamp'], name='admin_panel_timesta_8c448c_idx'),
        ),
    ]
