# Generated by Django 5.2.4 on 2025-10-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_add_visitor_analytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='session',
        ),
        migrations.DeleteModel(
            name='VisitorAnalytics',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='VisitorSession',
        ),
    ]
