# Generated by Django 5.2.4 on 2025-10-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_pageview_session_delete_visitoranalytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Anahtar Kelimeler'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='OG Açıklama'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/og/', verbose_name='OG Görsel'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='OG Başlık'),
        ),
    ]
