# Generated by Django 5.2.4 on 2025-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_blogpost_canonical_url_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermission',
            name='permission',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'Kullanıcı Yönetimi'), ('vendors', 'Esnaf Yönetimi'), ('support', 'Destek Talepleri'), ('blog', 'Blog Yönetimi'), ('content', 'İçerik Yönetimi'), ('analytics', 'İstatistikler'), ('settings', 'Sistem Ayarları'), ('definitions', 'Tanımlamalar'), ('live_support', 'Canlı Destek'), ('logs', 'Sistem Logları')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Domain Adı')),
                ('registrar', models.CharField(blank=True, max_length=255, verbose_name='Kayıt Şirketi')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Kayıt Tarihi')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('expiring_soon', 'Yakında Dolacak'), ('error', 'Hata')], default='active', max_length=20, verbose_name='Durum')),
                ('days_until_expiry', models.IntegerField(blank=True, null=True, verbose_name='Kalan Gün')),
                ('nameservers', models.JSONField(blank=True, default=list, verbose_name="Name Server'lar")),
                ('admin_email', models.EmailField(blank=True, max_length=254, verbose_name='Admin E-posta')),
                ('tech_email', models.EmailField(blank=True, max_length=254, verbose_name='Teknik E-posta')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Otomatik Yenileme')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Son Kontrol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domainler',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='admin_panel_status_a47333_idx'), models.Index(fields=['expiration_date'], name='admin_panel_expirat_f97016_idx'), models.Index(fields=['days_until_expiry'], name='admin_panel_days_un_8e1e6f_idx')],
            },
        ),
    ]
