# Generated by Django 5.2.4 on 2025-10-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_adminpermission_permission_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_registered', 'Kullanıcı Kaydı'), ('vendor_created', 'Esnaf Oluşturuldu'), ('support_ticket', 'Destek Talebi'), ('blog_published', 'Blog Yayınlandı'), ('user_verified', 'Kullanıcı Doğrulandı'), ('vendor_verified', 'Esnaf Doğrulandı')], db_index=True, max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Aktivite Logu',
                'verbose_name_plural': 'Aktivite Logları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type'], name='admin_panel_activit_76b2a8_idx'), models.Index(fields=['created_at'], name='admin_panel_created_77c91f_idx'), models.Index(fields=['activity_type', 'created_at'], name='admin_panel_activit_93cd0f_idx')],
            },
        ),
    ]
