# Generated by Django 5.2.4 on 2025-10-17 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='activity_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Aktivite Verisi'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='activity_type',
            field=models.CharField(choices=[('system', 'Sistem'), ('user_registered', 'Kullanıcı Kaydı'), ('vendor_created', 'Esnaf Oluşturuldu'), ('support_ticket', 'Destek Talebi'), ('blog_published', 'Blog Yayınlandı'), ('user_verified', 'Kullanıcı Doğrulandı'), ('vendor_verified', 'Esnaf Doğrulandı')], db_index=True, default='system', max_length=20, verbose_name='Aktivite Türü'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['activity_type'], name='admin_panel_activit_290d98_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['activity_type', 'created_at'], name='admin_panel_activit_94c54d_idx'),
        ),
    ]
