# Generated by Django 5.2.4 on 2025-10-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_systemlog_activity_data_systemlog_activity_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
