# Generated by Django 5.2.4 on 2025-11-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_blogpost_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_by',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.adminuser', verbose_name='Yazar (Admin)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts_created', to='admin_panel.adminuser', verbose_name='Oluşturan (Admin)'),
        ),
    ]
