# Generated by Django 5.2.4 on 2025-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_remove_blogpost_author_remove_blogpost_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=150, verbose_name='Öne Çıkan Görsel Alt Metin'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_alt',
            field=models.CharField(blank=True, max_length=150, verbose_name='OG Görsel Alt Metin'),
        ),
    ]
