# Generated by Django 5.2.4 on 2025-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_blogpost_featured_image_alt_blogpost_og_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
