# Generated by Django 5.2.4 on 2025-12-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='AuditLog_user_id_b11a9e_idx',
            old_name='audit_log_user_id_b41b02_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='AuditLog_action_396d2f_idx',
            old_name='audit_log_action_23c5f1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='AuditLog_ip_addr_39ba87_idx',
            old_name='audit_log_ip_addr_9ac2a1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='AuditLog_retenti_1175a6_idx',
            old_name='audit_log_retenti_f84c9c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='AuditLog_timesta_b6dd0b_idx',
            old_name='audit_log_timesta_9d0b56_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='AuditLog',
        ),
    ]
