# Generated by Django 5.2.4 on 2025-07-28 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('business_type', models.CharField(choices=[('sahis', 'Şahıs Şirketi'), ('limited', 'Limited Şirketi'), ('anonim', 'Anonim Şirketi'), ('esnaf', 'Esnaf')], max_length=16)),
                ('company_title', models.CharField(max_length=150)),
                ('tax_office', models.CharField(max_length=100)),
                ('tax_no', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='vendor_photos/')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('subdistrict', models.CharField(max_length=128)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_birthdate', models.DateField()),
                ('manager_tc', models.CharField(max_length=11)),
                ('manager_phone', models.CharField(max_length=20)),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
                ('service_areas', models.ManyToManyField(blank=True, to='core.servicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
