# Generated by Django 5.2.4 on 2025-08-06 14:15

import core.utils.avatar
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('business_type', models.CharField(choices=[('sahis', 'Şahıs Şirketi'), ('limited', 'Limited Şirketi'), ('anonim', 'Anonim Şirketi'), ('esnaf', 'Esnaf')], max_length=16)),
                ('company_title', models.CharField(max_length=150)),
                ('tax_office', models.CharField(max_length=100)),
                ('tax_no', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='vendor_photos/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.utils.avatar.avatar_upload_path)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('subdistrict', models.CharField(max_length=128)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('unavailable_dates', models.JSONField(blank=True, default=list)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_birthdate', models.DateField()),
                ('manager_tc', models.CharField(max_length=11)),
                ('manager_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brands', models.ManyToManyField(blank=True, to='core.carbrand', verbose_name='Hizmet Verilen Araba Markaları')),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
                ('service_areas', models.ManyToManyField(blank=True, to='core.servicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('service_description', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
