# Generated by Django 5.2.4 on 2025-11-24 13:07

import django.core.validators
import django.db.models.deletion
import vendors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('business_type', models.CharField(choices=[('sahis', 'Şahıs Şirketi'), ('limited', 'Limited Şirketi'), ('anonim', 'Anonim Şirketi'), ('esnaf', 'Esnaf')], max_length=16)),
                ('company_title', models.CharField(max_length=150)),
                ('tax_office', models.CharField(max_length=100)),
                ('tax_no', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('business_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('subdistrict', models.CharField(max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Enlem', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Boylam', max_digits=9, null=True)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('unavailable_dates', models.JSONField(blank=True, default=list)),
                ('manager_birthdate', models.DateField()),
                ('manager_tc', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brands', models.ManyToManyField(blank=True, to='core.carbrand', verbose_name='Hizmet Verilen Araba Markaları')),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
                ('service_areas', models.ManyToManyField(blank=True, to='core.servicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'VendorProfile',
            },
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vendors.models.vendor_gallery_upload_path)),
                ('description', models.CharField(blank=True, help_text='Görsel açıklaması (opsiyonel)', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Sıralama için kullanılır')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Esnaf Görseli',
                'verbose_name_plural': 'Esnaf Görselleri',
                'db_table': 'VendorImage',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('appointment', 'Randevu'), ('quote', 'Fiyat Teklifi'), ('emergency', 'Acil Yardım'), ('part', 'Parça Talebi')], default='quote', max_length=20)),
                ('vehicle_info', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('last_offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_offered_days', models.IntegerField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('unread_for_vendor', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('responded', 'Yanıtlandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('closed', 'Kapatıldı')], default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='İptal Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='vendors.vendorprofile')),
            ],
            options={
                'db_table': 'ServiceRequest',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('service_description', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vendors.vendorprofile')),
            ],
            options={
                'db_table': 'Appointment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('month_bucket', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_calls', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='vendors.vendorprofile')),
            ],
            options={
                'db_table': 'VendorCall',
                'indexes': [models.Index(fields=['vendor', 'month_bucket'], name='VendorCall_vendor__0d50f8_idx'), models.Index(fields=['vendor', 'created_at'], name='VendorCall_vendor__a38ba4_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'ip_hash', 'month_bucket'), name='uniq_call_vendor_ip_month')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5 arası puanlama', validators=[django.core.validators.MinValueValidator(1, message='Puan en az 1 olmalıdır'), django.core.validators.MaxValueValidator(5, message='Puan en fazla 5 olabilir')])),
                ('comment', models.TextField()),
                ('service_date', models.DateField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.vendorprofile')),
            ],
            options={
                'db_table': 'Review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_read'], name='Review_vendor__8b6541_idx'), models.Index(fields=['vendor', 'created_at'], name='Review_vendor__155a03_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('month_bucket', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='vendors.vendorprofile')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'VendorView',
                'indexes': [models.Index(fields=['vendor', 'month_bucket'], name='VendorView_vendor__37e556_idx'), models.Index(fields=['vendor', 'created_at'], name='VendorView_vendor__0650c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'ip_hash', 'ua_hash', 'month_bucket'), name='uniq_view_vendor_ip_ua_month')],
            },
        ),
    ]
