# Generated by Django 5.2.4 on 2025-07-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='longitude',
        ),
    ]
