# Generated by Django 5.2.4 on 2025-08-07 16:41

from django.db import migrations


def migrate_manager_phone_to_user(apps, schema_editor):
    """VendorProfile'daki manager_phone verilerini CustomUser'a taşı"""
    CustomUser = apps.get_model('core', 'CustomUser')
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    
    # VendorProfile'daki manager_phone verilerini CustomUser'a taşı
    for vendor in VendorProfile.objects.all():
        if vendor.manager_phone and not vendor.user.phone_number:
            vendor.user.phone_number = vendor.manager_phone
            vendor.user.save()


def reverse_migrate_phone_to_manager(apps, schema_editor):
    """Geri alma işlemi"""
    CustomUser = apps.get_model('core', 'CustomUser')
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    
    # Geri alma işlemi
    for vendor in VendorProfile.objects.all():
        if vendor.user.phone_number:
            vendor.manager_phone = vendor.user.phone_number
            vendor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('core', '0002_customuser_is_verified_customuser_phone_number_and_more'),
    ]

    operations = [
        # Data migration - manager_phone verilerini taşı
        migrations.RunPython(
            migrate_manager_phone_to_user,
            reverse_migrate_phone_to_manager
        ),
        # manager_phone alanını kaldır
        migrations.RemoveField(
            model_name='vendorprofile',
            name='manager_phone',
        ),
    ]
