# Generated by Django 5.2.4 on 2025-07-29 14:16

import core.utils.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.avatar.avatar_upload_path),
        ),
    ]
