# Generated by Django 5.2.4 on 2025-08-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendorprofile_manager_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='phone',
        ),
    ]
