# Generated by Django 5.2.4 on 2025-08-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendorprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
