# Generated by Django 5.2.4 on 2025-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
