# Generated by Django 5.2.4 on 2025-08-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorprofile_business_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_phone',
            field=models.CharField(max_length=20),
        ),
    ]
