# Generated by Django 5.2.4 on 2025-08-02 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorprofile_unavailable_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
