# Generated by Django 5.2.4 on 2025-08-11 14:49

from django.db import migrations


def migrate_vendor_data_to_customuser(apps, schema_editor):
    """Mevcut vendor profil verilerini CustomUser'a taşı"""
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    CustomUser = apps.get_model('core', 'CustomUser')
    
    for vendor_profile in VendorProfile.objects.all():
        user = vendor_profile.user
        
        # Eğer CustomUser'da first_name yoksa, VendorProfile'dan manager_name'i al
        if not user.first_name and hasattr(vendor_profile, 'manager_name'):
            user.first_name = vendor_profile.manager_name or ''
        
        # Eğer CustomUser'da avatar yoksa, VendorProfile'dan al
        if not user.avatar and hasattr(vendor_profile, 'avatar') and vendor_profile.avatar:
            user.avatar = vendor_profile.avatar
        
        # Eğer CustomUser'da avatar yoksa, VendorProfile'dan profile_photo'yu al
        if not user.avatar and hasattr(vendor_profile, 'profile_photo') and vendor_profile.profile_photo:
            user.avatar = vendor_profile.profile_photo
        
        user.save()


def reverse_migrate_vendor_data(apps, schema_editor):
    """Geri almak için (gerekirse)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendorprofile_business_phone'),
        ('core', '0005_customuser_avatar_alter_customuser_first_name_and_more'),
    ]

    operations = [
        # Önce veri taşıma
        migrations.RunPython(migrate_vendor_data_to_customuser, reverse_migrate_vendor_data),
        
        # Sonra field'ları kaldır
        migrations.RemoveField(
            model_name='vendorprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='profile_photo',
        ),
    ]
