# Generated by Django 5.2.4 on 2025-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_remove_vendorprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='customer_email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='customer_name',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
