# Generated by Django 5.2.4 on 2025-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carbrand'),
        ('vendors', '0006_vendorprofile_created_at_vendorprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='car_brands',
            field=models.ManyToManyField(blank=True, to='core.carbrand', verbose_name='Hizmet Verilen Araba Markaları'),
        ),
    ]
