# Generated by Django 5.2.4 on 2025-08-21 13:06

import core.utils.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_rename_customer_email_appointment_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.avatar.avatar_upload_path),
        ),
    ]
