# Generated by Django 5.2.4 on 2025-08-26 20:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vendorupgraderequest_address_and_more'),
        ('vendors', '0008_vendorprofile_store_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5 arası puanlama', validators=[django.core.validators.MinValueValidator(1, message='Puan en az 1 olmalıdır'), django.core.validators.MaxValueValidator(5, message='Puan en fazla 5 olabilir')])),
                ('comment', models.TextField()),
                ('service_date', models.DateField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_read'], name='vendors_rev_vendor__ab463d_idx'), models.Index(fields=['vendor', 'created_at'], name='vendors_rev_vendor__01fdf5_idx')],
            },
        ),
    ]
