# Generated by Django 5.2.4 on 2025-09-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
