# Generated by Django 5.2.4 on 2025-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_servicerequest_client_phone_servicerequest_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('appointment', 'Randevu'), ('quote', 'Fiyat Teklifi'), ('emergency', 'Acil Yardım'), ('part', 'Parça Talebi')], default='quote', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='unread_for_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('responded', 'Yanıtlandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('closed', 'Kapatıldı')], default='pending', max_length=20),
        ),
    ]
