# Generated by Django 5.2.4 on 2025-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_servicerequest_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='last_offered_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='last_offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
