# Generated by Django 5.2.4 on 2025-09-23 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_servicerequest_last_offered_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('month_bucket', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('month_bucket', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='vendors_ser_vendor__1942e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='vendors_ser_user_id_6945b7_idx',
        ),
        migrations.AddField(
            model_name='vendorcall',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendorcall',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorview',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendorview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vendorcall',
            index=models.Index(fields=['vendor', 'month_bucket'], name='vendors_ven_vendor__5ee906_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcall',
            index=models.Index(fields=['vendor', 'created_at'], name='vendors_ven_vendor__c806e0_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorview',
            index=models.Index(fields=['vendor', 'month_bucket'], name='vendors_ven_vendor__ff8875_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorview',
            index=models.Index(fields=['vendor', 'created_at'], name='vendors_ven_vendor__5167f3_idx'),
        ),
    ]
