# Generated by Django 5.2.4 on 2025-09-23 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_vendorcall_vendorview_alter_servicerequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendorcall',
            constraint=models.UniqueConstraint(fields=('vendor', 'ip_hash', 'month_bucket'), name='uniq_call_vendor_ip_month'),
        ),
        migrations.AddConstraint(
            model_name='vendorview',
            constraint=models.UniqueConstraint(fields=('vendor', 'ip_hash', 'ua_hash', 'month_bucket'), name='uniq_view_vendor_ip_ua_month'),
        ),
    ]
