# Generated by Django 5.2.4 on 2025-10-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_vendorcall_uniq_call_vendor_ip_month_and_more'),
        ('vendors', '0017_remove_vendorprofile_store_logo'),
    ]

    operations = [
    ]
