# Generated by Django 5.2.4 on 2025-10-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_merge_20251001_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Enlem', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Boylam', max_digits=9, null=True),
        ),
    ]
