# Generated by Django 5.2.4 on 2025-11-13 11:43

import django.db.models.deletion
import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_vendorprofile_latitude_vendorprofile_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vendors.models.vendor_gallery_upload_path)),
                ('description', models.CharField(blank=True, help_text='Görsel açıklaması (opsiyonel)', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Sıralama için kullanılır')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Esnaf Görseli',
                'verbose_name_plural': 'Esnaf Görselleri',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
