# Generated by Django 5.2.4 on 2025-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_vendorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='İptal Nedeni'),
        ),
    ]
