"""
Django settings for backend project - Production Environment.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is required in production!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Security Settings - Production
ALLOWED_HOSTS = [
    'admin.sanayicin.com',
    'sanayicin.com',
    'www.sanayicin.com',
    'api.sanayicin.com',
    'localhost',
    '127.0.0.1',
]

# Security Headers - Production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Additional Security Headers (middleware ile eklenecek)
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# SSL/HTTPS Settings - Production'da aktif
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True').lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True').lower() == 'true'
SESSION_COOKIE_DOMAIN = os.environ.get('SESSION_COOKIE_DOMAIN', '.sanayicin.com')
CSRF_COOKIE_DOMAIN = os.environ.get('CSRF_COOKIE_DOMAIN', '.sanayicin.com')
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')

# Hostinger API Configuration
HOSTINGER_API_KEY = os.environ.get('HOSTINGER_API_KEY')

# Resend Email Configuration
RESEND_API_KEY = os.environ.get('RESEND_API_KEY')
RESEND_SMTP_PORT = int(os.environ.get('RESEND_SMTP_PORT', '465'))
RESEND_SMTP_USERNAME = os.environ.get('RESEND_SMTP_USERNAME', 'resend')
RESEND_SMTP_HOST = os.environ.get('RESEND_SMTP_HOST', 'smtp.resend.com')

# Email Backend - Production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'core',
    'vendors',
    'chat',
    'admin_panel',
    'auditlog',  # Audit Log app
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'core.middleware.CORSBlockingMiddleware',
    'core.middleware.RealIPMiddleware',  # Real IP middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',  # Güvenlik başlıkları için
]

# CORS Security - Production
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'
CORS_ALLOWED_ORIGINS = [
    "https://admin.sanayicin.com",
    "http://admin.sanayicin.com",
    "https://sanayicin.com",
    "https://www.sanayicin.com",
    "https://esnaf.sanayicin.com",
]

# CORS Additional Settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

# Database - Production (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'sanayicin'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000',  # 30 saniye query timeout
        },
        # Connection pooling - Yüksek trafik için
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),  # 10 dakika
        'ATOMIC_REQUESTS': True,  # Her request transaction içinde
    }
}

# Cache Configuration - Production (Redis)
# Yüksek trafik için Redis connection pool ayarları
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        # Django'nun native Redis backend'i connection pooling'i otomatik yönetir
        # Yüksek trafik için Redis server'da maxclients ayarını artırın
    }
}

# Channels config - Production (Redis)
ASGI_APPLICATION = 'main.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.environ.get('REDIS_URL', 'redis://localhost:6379/0')],
        },
    },
}

# Email Verification Settings
EMAIL_VERIFICATION_CODE_EXPIRY_MINUTES = int(os.environ.get('EMAIL_VERIFICATION_CODE_EXPIRY_MINUTES', '15'))
EMAIL_VERIFICATION_MAX_ATTEMPTS = int(os.environ.get('EMAIL_VERIFICATION_MAX_ATTEMPTS', '3'))
EMAIL_VERIFICATION_MAX_VERIFY_ATTEMPTS = int(os.environ.get('EMAIL_VERIFICATION_MAX_VERIFY_ATTEMPTS', '5'))

# SMS/OTP Settings - İletiMerkezi
ILETIMERKEZI_API_NAME = os.environ.get('ILETIMERKEZI_API_NAME', 'sanayicin')
ILETIMERKEZI_API_KEY = os.environ.get('ILETIMERKEZI_API_KEY')
ILETIMERKEZI_API_HASH = os.environ.get('ILETIMERKEZI_API_HASH')
ILETIMERKEZI_SENDER = os.environ.get('ILETIMERKEZI_SENDER', 'APITEST')

# SMS Verification Settings
SMS_VERIFICATION_CODE_EXPIRY_MINUTES = int(os.environ.get('SMS_VERIFICATION_CODE_EXPIRY_MINUTES', '5'))
SMS_VERIFICATION_MAX_ATTEMPTS = int(os.environ.get('SMS_VERIFICATION_MAX_ATTEMPTS', '3'))
SMS_VERIFICATION_MAX_VERIFY_ATTEMPTS = int(os.environ.get('SMS_VERIFICATION_MAX_VERIFY_ATTEMPTS', '5'))

# OTP Settings
OTP_CODE_EXPIRY_MINUTES = int(os.environ.get('OTP_CODE_EXPIRY_MINUTES', '5'))
OTP_MAX_ATTEMPTS = int(os.environ.get('OTP_MAX_ATTEMPTS', '3'))

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'core.CustomUser'

AUTHENTICATION_BACKENDS = [
    'core.backends.EmailBackend',
]

# JWT Settings - Production (güvenli süreler)
JWT_ACCESS_TOKEN_LIFETIME_HOURS = int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_HOURS', '1'))  # 1 saat (güvenlik için kısaltıldı)
JWT_REFRESH_TOKEN_LIFETIME_DAYS = int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_DAYS', '7'))  # 7 gün (30 günden düşürüldü)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=JWT_ACCESS_TOKEN_LIFETIME_HOURS),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=JWT_REFRESH_TOKEN_LIFETIME_DAYS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

# REST Framework - Production (Session Authentication - en güvenli)
# Yüksek trafik için optimize edilmiş rate limits
# Binlerce eş zamanlı kullanıcı için tasarlandı
# Rate limitler güvenlik ve performans dengesi gözetilerek ayarlandı
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',  # Session Authentication (en güvenli - tarayıcı tabanlı)
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.DefaultPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',  # Anonymous kullanıcılar için (güvenlik)
        'rest_framework.throttling.UserRateThrottle'  # Authenticated kullanıcılar için (yüksek trafik)
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Production - Yüksek trafik için optimize edilmiş limitler
        # Binlerce eş zamanlı kullanıcı için tasarlandı
        # Limitler güvenlik ve performans dengesi gözetilerek ayarlandı
        'anon': '5000/hour',  # ~1.4 req/s - Public sayfalar ve CSRF token için yeterli
        'user': '20000/hour',  # ~5.5 req/s - Aktif kullanıcılar için yeterli (dashboard, mesajlaşma vb.)
    },
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
} 

# Logging - Production (file-based technical logs)
# Tarih bilgisi tüm loglarda mevcut (asctime formatında)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s | %(levelname)-8s | %(name)s | %(pathname)s:%(lineno)d | %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'detailed': {
            'format': '%(asctime)s | %(levelname)-8s | %(name)s | %(pathname)s:%(lineno)d | %(funcName)s | %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        # Application Info Logları
        'info_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django_info.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Warning Logları
        'warning_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django_warning.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Error Logları
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django_error.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,  # Error logları daha uzun saklanır
            'formatter': 'detailed',
        },
        # Security Logları (teknik seviyede)
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django_security.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
    },
    'loggers': {
        # Django framework logları
        'django': {
            'handlers': ['info_file', 'warning_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Security logları
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # CSRF failures
        'django.security.csrf': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Application logları
        'core': {
            'handlers': ['info_file', 'warning_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'vendors': {
            'handlers': ['info_file', 'warning_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'admin_panel': {
            'handlers': ['info_file', 'warning_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Root logger
        '': {
            'handlers': ['info_file', 'warning_file', 'error_file'],
            'level': 'INFO',
        },
    },
}

# Internationalization
LANGUAGE_CODE = 'tr-tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
# Allow overriding MEDIA_ROOT via env in prod; fallback to project media folder
# BASE_DIR is backend/, but media folder is at project root, so go up one level
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR.parent / 'media')))

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Admin Panel Settings
ADMIN_PANEL_TOKEN_EXPIRY_HOURS = 24
ADMIN_PANEL_CACHE_TIMEOUT = 300  # 5 minutes

# Chat Settings
CHAT_MESSAGE_LIMIT = 100
CHAT_MESSAGE_RETENTION_DAYS = 30

# Vendor Settings
VENDOR_APPROVAL_REQUIRED = True
VENDOR_VERIFICATION_REQUIRED = True

# Support Settings
SUPPORT_TICKET_PRIORITY_CHOICES = [
    ('low', 'Düşük'),
    ('medium', 'Orta'),
    ('high', 'Yüksek'),
    ('urgent', 'Acil'),
]

SUPPORT_TICKET_STATUS_CHOICES = [
    ('open', 'Açık'),
    ('in_progress', 'İşlemde'),
    ('resolved', 'Çözüldü'),
    ('closed', 'Kapalı'),
]

# Blog Settings
BLOG_POSTS_PER_PAGE = 10
BLOG_FEATURED_POSTS_COUNT = 3

# Analytics Settings
ANALYTICS_RETENTION_DAYS = 90
ANALYTICS_BATCH_SIZE = 1000

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Session Settings
# Cookie isimleri: sabit ve anlamı belirsiz (obfuscation)
SESSION_COOKIE_NAME = os.environ.get('SESSION_COOKIE_NAME', "sa_rdx")
CSRF_COOKIE_NAME = os.environ.get('CSRF_COOKIE_NAME', "sa_cx")

SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# CSRF Settings
CSRF_COOKIE_AGE = 86400  # 24 hours
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'  # Güvenlik için Strict yapıldı (cross-site request'leri engeller) 