# Generated by Django 5.2.4 on 2025-11-24 13:07

import core.utils.avatar
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ServiceArea',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Admin tarafından gönderilen mesaj mı?')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destek Mesajı',
                'verbose_name_plural': 'Destek Mesajları',
                'db_table': 'SupportMessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('role', models.CharField(choices=[('client', 'Müşteri'), ('vendor', 'Esnaf'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=16)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/')),
                ('status', models.CharField(choices=[('open', 'Cevaplanmadı'), ('pending', 'Cevaplandı'), ('resolved', 'Çözüldü'), ('closed', 'Kapalı')], db_index=True, default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'db_table': 'SupportTicket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('plate_encrypted', models.TextField(blank=True)),
                ('engine_type', models.CharField(blank=True, choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('hibrit', 'Hibrit'), ('elektrik', 'Elektrik')], max_length=16)),
                ('kilometre', models.PositiveIntegerField(blank=True, null=True)),
                ('periodic_due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('periodic_due_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_notes', models.TextField(blank=True)),
                ('inspection_expiry', models.DateField(blank=True, null=True)),
                ('exhaust_emission_date', models.DateField(blank=True, null=True)),
                ('tire_change_date', models.DateField(blank=True, null=True)),
                ('traffic_insurance_expiry', models.DateField(blank=True, null=True)),
                ('casco_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Vehicle',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('requires_info', 'Bilgi Gerekli')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('business_type', models.CharField(choices=[('sahis', 'Şahıs Şirketi'), ('limited', 'Limited Şirketi'), ('anonim', 'Anonim Şirketi'), ('esnaf', 'Esnaf')], max_length=16)),
                ('company_title', models.CharField(max_length=150)),
                ('tax_office', models.CharField(max_length=100)),
                ('tax_no', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('subdistrict', models.CharField(max_length=128)),
                ('business_phone', models.CharField(max_length=20)),
                ('about', models.TextField(blank=True)),
                ('manager_birthdate', models.DateField()),
                ('manager_tc', models.CharField(max_length=11)),
                ('business_license', models.FileField(upload_to='business_licenses/')),
                ('tax_certificate', models.FileField(upload_to='tax_certificates/')),
                ('identity_document', models.FileField(upload_to='identity_documents/')),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('unavailable_dates', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Esnaf Yükseltme Talebi',
                'verbose_name_plural': 'Esnaf Yükseltme Talepleri',
                'db_table': 'VendorUpgradeRequest',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('client', 'Müşteri'), ('vendor', 'Esnaf')], db_index=True, default='client', max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('can_provide_services', models.BooleanField(default=False)),
                ('can_request_services', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.utils.avatar.avatar_upload_path)),
                ('about', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'CustomUser',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='car_brand_logos/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CarBrand',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='CarBrand_is_acti_1846f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EmailVerification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoriler',
                'db_table': 'Favorite',
                'ordering': ['-created_at'],
            },
        ),
    ]
