# Generated by Django 5.2.4 on 2025-08-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_email_verified_to_is_verified(apps, schema_editor):
    """Mevcut email_verified verilerini is_verified'a taşı"""
    CustomUser = apps.get_model('core', 'CustomUser')
    
    # Mevcut email_verified verilerini is_verified'a taşı
    CustomUser.objects.filter(email_verified=True).update(is_verified=True)
    
    # Mevcut doğrulanmış kullanıcıların verification_method'unu email yap
    CustomUser.objects.filter(is_verified=True).update(verification_method='email')


def reverse_migrate_is_verified_to_email_verified(apps, schema_editor):
    """Geri alma işlemi"""
    CustomUser = apps.get_model('core', 'CustomUser')
    
    # Geri alma işlemi
    CustomUser.objects.filter(is_verified=True).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Data migration - mevcut verileri taşı
        migrations.RunPython(
            migrate_email_verified_to_is_verified,
            reverse_migrate_is_verified_to_email_verified
        ),
    ]
