# Generated by Django 5.2.4 on 2025-11-24 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vendors.vendorprofile'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['name'], name='ServiceArea_name_43065a_idx'),
        ),
        migrations.AddField(
            model_name='category',
            name='service_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.servicearea'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportticket'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.carbrand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='car_brands',
            field=models.ManyToManyField(blank=True, to='core.carbrand'),
        ),
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.category'),
        ),
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='service_areas',
            field=models.ManyToManyField(blank=True, to='core.servicearea'),
        ),
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_upgrade_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='CustomUser_role_b2aabe_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='CustomUser_date_jo_ff9700_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'date_joined'], name='CustomUser_role_14688b_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['vendor', 'created_at'], name='Favorite_vendor__1b6563_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='Category_name_476266_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['service_area'], name='Category_service_422565_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='SupportTick_status_ef5b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='SupportTick_created_b4f19e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='SupportTick_status_bae879_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['ticket'], name='SupportMess_ticket__38695f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['created_at'], name='SupportMess_created_3ff824_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'brand'], name='Vehicle_user_id_1026df_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'inspection_expiry'], name='Vehicle_user_id_baee09_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'traffic_insurance_expiry'], name='Vehicle_user_id_9ecb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'casco_expiry'], name='Vehicle_user_id_32a0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorupgraderequest',
            index=models.Index(fields=['status'], name='VendorUpgra_status_676605_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorupgraderequest',
            index=models.Index(fields=['requested_at'], name='VendorUpgra_request_2650e0_idx'),
        ),
    ]
