# Generated by Django 5.2.4 on 2025-08-11 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_verified_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_provide_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_request_services',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Müşteri'), ('vendor', 'Esnaf'), ('admin', 'Admin')], default='client', max_length=16),
        ),
        migrations.CreateModel(
            name='VendorUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('requires_info', 'Bilgi Gerekli')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('business_type', models.CharField(choices=[('sahis', 'Şahıs Şirketi'), ('limited', 'Limited Şirketi'), ('anonim', 'Anonim Şirketi'), ('esnaf', 'Esnaf')], max_length=16)),
                ('company_title', models.CharField(max_length=150)),
                ('tax_office', models.CharField(max_length=100)),
                ('tax_no', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('subdistrict', models.CharField(max_length=128)),
                ('manager_birthdate', models.DateField()),
                ('manager_tc', models.CharField(max_length=11)),
                ('business_license', models.FileField(upload_to='business_licenses/')),
                ('tax_certificate', models.FileField(upload_to='tax_certificates/')),
                ('identity_document', models.FileField(upload_to='identity_documents/')),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('unavailable_dates', models.JSONField(blank=True, default=list)),
                ('car_brands', models.ManyToManyField(blank=True, to='core.carbrand')),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
                ('service_areas', models.ManyToManyField(blank=True, to='core.servicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_upgrade_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esnaf Yükseltme Talebi',
                'verbose_name_plural': 'Esnaf Yükseltme Talepleri',
                'ordering': ['-requested_at'],
            },
        ),
    ]
