# Generated by Django 5.2.4 on 2025-08-11 14:49

import core.utils.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_migrate_both_roles_and_set_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.avatar.avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
