# Generated by Django 5.2.4 on 2025-08-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_avatar_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
    ]
