# Generated by Django 5.2.4 on 2025-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='business_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='city',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vendorupgraderequest',
            name='district',
            field=models.CharField(default='', max_length=64),
        ),
    ]
