# Generated by Django 5.2.4 on 2025-08-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vendorupgraderequest_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorupgraderequest',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorupgraderequest',
            name='business_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorupgraderequest',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vendorupgraderequest',
            name='district',
            field=models.CharField(max_length=64),
        ),
    ]
