# Generated by Django 5.2.4 on 2025-09-26 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vendorupgraderequest_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('role', models.CharField(choices=[('client', 'Müşteri'), ('vendor', 'Esnaf'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=16)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('pending', 'Beklemede'), ('resolved', 'Çözüldü'), ('closed', 'Kapalı')], default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
