# Generated by Django 5.2.4 on 2025-10-01 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('plate_encrypted', models.TextField(blank=True)),
                ('engine_type', models.CharField(blank=True, choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('hibrit', 'Hibrit'), ('elektrik', 'Elektrik')], max_length=16)),
                ('kilometre', models.PositiveIntegerField(blank=True, null=True)),
                ('periodic_due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('periodic_due_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_notes', models.TextField(blank=True)),
                ('inspection_expiry', models.DateField(blank=True, null=True)),
                ('exhaust_emission_date', models.DateField(blank=True, null=True)),
                ('tire_change_date', models.DateField(blank=True, null=True)),
                ('traffic_insurance_expiry', models.DateField(blank=True, null=True)),
                ('casco_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'brand'], name='core_vehicl_user_id_e525c3_idx'), models.Index(fields=['user', 'inspection_expiry'], name='core_vehicl_user_id_5b3b69_idx'), models.Index(fields=['user', 'traffic_insurance_expiry'], name='core_vehicl_user_id_0ef080_idx'), models.Index(fields=['user', 'casco_expiry'], name='core_vehicl_user_id_d61d28_idx')],
            },
        ),
    ]
