# Generated by Django 5.2.4 on 2025-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Müşteri'), ('vendor', 'Esnaf'), ('admin', 'Admin'), ('editor', 'Editör'), ('support', 'Teknik Destek')], default='client', max_length=16),
        ),
    ]
