# Generated by Django 5.2.4 on 2025-10-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Müşteri'), ('vendor', 'Esnaf')], default='client', max_length=16),
        ),
    ]
