# Generated by Django 5.2.4 on 2025-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0015_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Müşteri'), ('vendor', 'Esnaf')], db_index=True, default='client', max_length=16),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Açık'), ('pending', 'Beklemede'), ('resolved', 'Çözüldü'), ('closed', 'Kapalı')], db_index=True, default='open', max_length=16),
        ),
        migrations.AddIndex(
            model_name='carbrand',
            index=models.Index(fields=['is_active'], name='core_carbra_is_acti_de366b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='core_custom_role_77f64b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='core_custom_date_jo_0d7823_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'date_joined'], name='core_custom_role_0ab4f8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='core_suppor_status_152db5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='core_suppor_created_985d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='core_suppor_status_19a22c_idx'),
        ),
    ]
