# Generated by Django 5.2.4 on 2025-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customuser_options_alter_carbrand_is_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='core_catego_name_6ef604_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['service_area'], name='core_catego_service_4e932c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['name'], name='core_servic_name_8fbf99_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['ticket'], name='core_suppor_ticket__8e0e84_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['created_at'], name='core_suppor_created_6808ad_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorupgraderequest',
            index=models.Index(fields=['status'], name='core_vendor_status_c7d700_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorupgraderequest',
            index=models.Index(fields=['requested_at'], name='core_vendor_request_9ee11f_idx'),
        ),
    ]
