# Generated by Django 5.2.4 on 2025-10-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_category_core_catego_name_6ef604_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='core_vehicl_user_id_717fcb_idx',
            old_name='core_vehicl_user_id_e525c3_idx',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.carbrand'),
        ),
    ]
