# Generated by Django 5.2.4 on 2025-11-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_support_category'),
        ('vendors', '0019_vendorprofile_latitude_vendorprofile_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportCategory',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Cevaplanmadı'), ('pending', 'Cevaplandı'), ('resolved', 'Çözüldü'), ('closed', 'Kapalı')], db_index=True, default='open', max_length=16),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['vendor', 'created_at'], name='core_favori_vendor__2c71cb_idx'),
        ),
    ]
