# Generated by Django 5.2.4 on 2025-11-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sms_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sms_verification_code',
        ),
        migrations.DeleteModel(
            name='SMSVerification',
        ),
    ]
